; PlatformIO Project Configuration File
;
; Sensor de Ré - ESP32
; Sensor ultrassônico HC-SR04 + Buzzer + 6 LEDs
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
